# Generated by Django 4.0.2 on 2022-02-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bugdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budid', models.IntegerField()),
                ('bug_decs', models.CharField(max_length=50)),
                ('on_create', models.DateTimeField()),
                ('on_update', models.DateTimeField()),
                ('bugstatus', models.CharField(max_length=50)),
                ('bugtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('projectname', models.CharField(max_length=50)),
                ('companyname', models.CharField(max_length=50)),
                ('projectstatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.IntegerField()),
                ('rolename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('on_joinnig', models.DateTimeField()),
                ('on_resign', models.DateTimeField()),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.role')),
            ],
        ),
    ]
