# Generated by Django 4.0.2 on 2022-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_bugdetail_id_remove_project_id_remove_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
